
stages:
  - test
  - deploy

unittest:
  stage: test
  services:
    - name: mongo
      alias: mongo
  script:
    - make coverage
    - make test

push_image_to_aliyun:
  stage: deploy
  tags:
    - shell
  only:
    - tags
  before_script:
    - docker login registry.cn-hangzhou.aliyuncs.com  -u $ALIYUN_DOCKER_USERNAME -p $ALIYUN_DOCKER_PASSWORD
  script:
    - docker build -f Dockerfile -t $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG .
    - docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG registry.cn-hangzhou.aliyuncs.com/jinchongzi/$CI_PROJECT_NAME:$CI_COMMIT_TAG
    - docker push registry.cn-hangzhou.aliyuncs.com/jinchongzi/$CI_PROJECT_NAME:$CI_COMMIT_TAG
    - docker rmi registry.cn-hangzhou.aliyuncs.com/jinchongzi/$CI_PROJECT_NAME:$CI_COMMIT_TAG
    - docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG registry.cn-hangzhou.aliyuncs.com/jinchongzi/$CI_PROJECT_NAME:latest
    - docker push registry.cn-hangzhou.aliyuncs.com/jinchongzi/$CI_PROJECT_NAME:latest
    - docker rmi registry.cn-hangzhou.aliyuncs.com/jinchongzi/$CI_PROJECT_NAME:latest
