site_name: Paperplane纸飞机系统使用说明
site_description: Paperplane纸飞机系统是金牛智道的智能投资模拟服务后台
site_author: 邱承
copyright: 金牛智道 2019
theme:
  name: 'material'
  logo: 'logo.png'
  palette:
      primary: 'blue'
      accent: 'indigo'
  feature:
    tabs: true
nav:
    - 首页: index.md
    - 基本概念: concepts.md
    - 如何使用:
      - 使用步骤: usage/使用步骤.md
      - 机器人的功能: usage/机器人的功能.md
      - 模拟交易撮合规则: usage/模拟交易撮合规则.md
      - 装备的分类及功能: usage/装备的分类及功能.md
      - 严格的评估评级体系: usage/严格的评估评级体系.md
    - 接口说明:
      - 数据字典: sdk/数据字典.md
      - 接口定义: sdk/接口定义.md
    - 服务器安装: install.md
    - 常见问题: FAQ.md
    - TODO: TODO.md
    - Changelog: changelog.md
markdown_extensions:
  - admonition
  - codehilite:
      linenums: true
extra:
  disqus: 'jin-niu-zhi-dao-1'
