site_name: Paperplane纸飞机系统使用说明
site_description: Paperplane纸飞机系统是金牛智道的智能投资模拟服务后台
site_author: 邱承
copyright: 金牛智道 2019
theme:
  name: 'material'
  logo: 'logo.png'
  palette:
      primary: 'blue'
      accent: 'indigo'
  feature:
    tabs: true
nav:
    - 首页: readme.md
    - 参数: settings.md
    - 接口说明:
      - 数据字典: sdk/数据字典.md
      - 接口定义: sdk/接口定义.md
    - 常见问题: FAQ.md
    - TODO: TODO.md
    - Changelog: changelog.md
markdown_extensions:
  - admonition
  - codehilite:
      linenums: true
extra:
  disqus: 'jin-niu-zhi-dao-1'
